# Generated by Django 5.0.6 on 2024-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maso', models.CharField(max_length=10)),
                ('ho', models.CharField(max_length=30)),
                ('ten', models.CharField(max_length=10)),
                ('qt1', models.FloatField()),
                ('qt2', models.FloatField()),
                ('mid', models.FloatField()),
                ('final', models.FloatField()),
            ],
        ),
    ]
